resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/001ec3576ef3bda04cf5bcccdd9a00991835d1a7/snapshot.yaml

packages:
  - ./typed-transitions
  - ./typed-protocols
  - ./typed-protocols-cbor
  - ./network-mux
  - ./ouroboros-network
  - ./ouroboros-network-testing
  - ./ouroboros-consensus
  - ./io-sim
  - ./io-sim-classes
  - ./ntp-client
  - ./Win32-network

extra-deps:
  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 5b91f7a10465ae1215522a39d42df7e970ab8e8f
    subdirs:
      - contra-tracer

  - git: https://github.com/input-output-hk/cardano-base
    commit: 8c6869e63dca15e8fd7e455e65bda1295f2bbfb8
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: 11b674a10e76ab266a37225d82955fd8b1f80e27
    subdirs:
      - byron/semantics/executable-spec
      - byron/ledger/executable-spec
      - byron/chain/executable-spec

  # Needed for `cardano-ledger-specs`
  - git: https://github.com/input-output-hk/goblins
    commit: 26d35ad52fe9ade3391532dbfeb2f416f07650bc
  - moo-1.2
  - gray-code-0.3.1

  - git: https://github.com/input-output-hk/cardano-ledger
    commit: 181f69af290412abecefc07e1b26e77a453755ff
    subdirs:
      - cardano-ledger
      - cardano-ledger/test
      - crypto
      - crypto/test

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: ad19158c7599bc5d50fe7cb0111a1488a139a381
    subdirs:
      - .
      - test

  - git: https://github.com/advancedtelematic/quickcheck-state-machine
    commit: 41718e9b17e3151178ce27600f84ca1d9d852c65
    subdirs:
      - .

  - bimap-0.4.0
  - binary-0.8.7.0
  - generic-monoid-0.1.0.0
  - graphviz-2999.20.0.3
  - hedgehog-quickcheck-0.1.1
  - splitmix-0.0.2
  - time-units-1.0.0
  - tasty-hedgehog-1.0.0.1
  - Unique-0.4.7.6
  - these-0.8
  - assoc-1
  - QuickCheck-2.13.2@sha256:ad4e5adbd1c9dc0221a44307b992cb040c515f31095182e47aa7e974bc461df1,6952
  - markov-chain-usage-model-0.0.0@sha256:1afa95faeb9213c4d960a669190078b41b89169462b8edd910472980671ba8c0,2112

  # Windows only
  - Win32-2.6.2.0

nix:
  shell-file: nix/stack-shell.nix
